MaikuB/flutter_local_notifications

android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
android/src/main/java/com/dexterous/flutterlocalnotifications/models/Time.java
example/lib/main.dart
ios/Classes/FlutterLocalNotificationsPlugin.m
ios/Classes/NotificationTime.h
ios/Classes/NotificationTime.m
lib/flutter_local_notifications.dart

I've implemented it for android, I'll try to make it work for IOS as well
Caveat: The notification time is hardcoded in the example app

Implemented daily notification with custom time

---

ios/Classes/FlutterLocalNotificationsPlugin.m

Description
---
- Notifications scheduled for a time earlier in the day than the time the code was called resulted in invalid triggers (never getting fired).
- For instance, it's noon and you are scheduling a morning notification to be shown daily. These wouldn't fire because our trigger is initialized with today's date resulting in the impossibility to be executed.
What Was Changed
---
- Drop `NSCalendarUnitYear|NSCalendarUnitMonth|NSCalendarUnitDay` from the `NSDateComponents` we use for our `UNCalendarNotificationTrigger`. The trigger should ignore the year, month, and day and instead only be fired when it's the appropriate time and/or weekday.
- Specify the calendar on the `NSDateComponents` since we no longer init with components from a date and calendar.
Testing
---
- Regression …

[#61] iOS: Refactor date components used in repeat notification scheduling.

---

example/ios/Flutter/AppFrameworkInfo.plist
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner/Info.plist
ios/Classes/FlutterLocalNotificationsPlugin.m

On devices before iOS 10, scheduled notifications were immediately notified.
Switching Flutter from dev branch to master branch improved the problem of being truncated between Flutter and Objective-C.
However, the problem truncated within Objective-C still occurred.
We fixed this by replacing integerValue with longLongValue.
To check this fix you need to switch Flutter to master branch.
The example application was designed to work only with arm64 devices. Probably this plugin has been tested only on arm64 devices. This problem may only occur on 32 bit devices. We have made this application work on devices that are not arm64. When you test this change, we would like you to test even devices that are not arm64.

#140 Fixed secondsSinceEpoch being truncated on iOS

---

android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Hi,
When you are running this plugin with multiple isolates, the use of a static method channel means that the first instance of the plugin for one of the isolates get over written by the instance for the new isolate.
Hence you can't send notification intents to both dart isolates. Moving the method channel within the plugin gets around this issue.
Not sure if it causes other issues however. I'm not fully sure I understand why you created it as static. There may be a very good reason!
Here is the PR.
Cheers

Support multi plugins for background operation

---

android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationPrecision.java
android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
lib/src/flutter_local_notifications.dart
lib/src/platform_specifics/android/enums.dart
lib/src/platform_specifics/android/notification_details.dart
test/flutter_local_notifications_test.dart

#216 and other pull request #239 
I tried to implement with a new class as you mentioned in that thread.
I wanted to avoid having 'exact' as the default, because the whole point of the change to inexact was so Android can manage wakelocks better etc.
I also wanted to avoid a breaking change, so I made it fall back to 'inexact' if not specified, but that basically does make it a breaking-ish change, because the old behavior was exact.
In extending the AndroidNotificationDetails class, I had to re-specify all the defaults, which seems not so good. I don't know if there's a better way to do it.
Finally, it would be good to have an enum in the java side like the dart, but it ended up converting between ints and the enum and it was a bit complicated.

Implement precision on ScheduledAndroidNotificationDetails

---

ios/Classes/FlutterLocalNotificationsPlugin.h
ios/Classes/FlutterLocalNotificationsPlugin.m

Related: #278 
This PR moves class variables to instance variables to address issues when this plugin is registered multiple times.
Previously, when the plugin is registered a second time, the channel, registrar, and UNUserNotificationCenter delegate would be recreated/set to the new plugin. As these variables were class variables this would affect all instances of the plugin.

Instance variables

---

android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Changed `FLAG_CANCEL_CURRENT` to `FLAG_UPDATE_CURRENT` when creating PendingIntents in cancelling functions.  `FLAG_CANCEL_CURRENT ` will cancel the existing one and create a new PendingIntent, causing failure when cancel previous alarms which are created with the previous PendingIntents.

changed FLAG_CANCEL_CURRENT to FLAG_UPDATE_CURRENT in cancelling alarms

---

README.md
android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
example/lib/main.dart
lib/src/platform_specifics/android/enums.dart
lib/src/platform_specifics/android/notification_details.dart

With this pull request I want to add the ability to configure the notification visibility on the lockscreen. This in an Android-only feature.
Official docs [here](https://developer.android.com/reference/android/app/Notification.html#visibility).

Added notification visibility (Android only)

---

flutter_local_notifications/README.md
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart

Currently notification permissions can only be requested when plugin is
initialized. In some cases this may result in suboptimal user
experience, when user will be asked for the notification permission
before he would event decide if he want to be notified by application.
This patch adds 'requestPermissions' method that may be used later on
for asking user to grant application notification permission. This way
all the notification handlers can be initialized immediately after app
startup. Then later on, when user actually decide to use local
notifications 'requestPermissions' method will be used to as him for
required permissions.
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. …

[flutter_local_notifications] add support for delayed notification permission request on iOS

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart

now the developer can configure displaying the notification create or update time. default is true in android. just use **showWhen** attribute in AndroidNotificationDetails.
`  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
'your channel id', 'your channel name', 'your channel description',
showWhen : false , enableVibration : false , autoCancel : false ,onlyAlertOnce: true, ongoing: true , playSound: false , icon: 'app_icon' );`

[flutter_local_notifications] add ability to toggle showing notification timestamp on Android

---

flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/example/pubspec.yaml
flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/ios/Classes/NotificationAttachment.h
flutter_local_notifications/ios/Classes/NotificationAttachment.m
flutter_local_notifications/ios/Classes/NotificationDetails.h
flutter_local_notifications/lib/flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/ios/notification_attachment.dart
flutter_local_notifications/lib/src/platform_specifics/ios/notification_details.dart
flutter_local_notifications/test/flutter_local_notifications_test.dart

This PR adds ability to pass attachments from Dart to the native iOS code and set them into UNNotificationContent of a new notification.

[flutter_local_notifications] add ability to associate iOS user notifications with attachments

---

flutter_local_notifications/README.md
flutter_local_notifications/example/analysis_options.yaml
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/android/bitmap.dart
flutter_local_notifications/lib/src/platform_specifics/android/enums.dart
flutter_local_notifications/lib/src/platform_specifics/android/icon.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_sound.dart
flutter_local_notifications/lib/src/platform_specifics/android/person.dart
flutter_local_notifications/lib/src/platform_specifics/android/styles/big_picture_style_information.dart
flutter_local_notifications/lib/src/platform_specifics/android/styles/big_text_style_information.dart
flutter_local_notifications/lib/src/platform_specifics/android/styles/default_style_information.dart
flutter_local_notifications/lib/src/platform_specifics/android/styles/inbox_style_information.dart
flutter_local_notifications/lib/src/platform_specifics/android/styles/media_style_information.dart
flutter_local_notifications/lib/src/platform_specifics/android/styles/messaging_style_information.dart
flutter_local_notifications/lib/src/platform_specifics/android/styles/style_information.dart

[flutter_local_notifications] remove the need to specify certain enum properties for Android notifications

---

.cirrus.yml

Apparently there is no more `emulator-headless`: https://stackoverflow.com/a/59250326

Fixed missing emulator-headless

---

flutter_local_notifications/README.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationBootReceiver.java
flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml

I've added the action to the example's manifest and the README.
Changed the log message to something more generic
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications])
Fixes Issue #689

Added  MY_PACKAGE_REPLACED action handling in BootReceiver

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Calling 
```java 
FlutterLocalNotificationsPlugin.registerWith(...
```
from background throws null pointer at
```java
launchIntent = mainActivity.getIntent();
```
Demo app repo here where we FirebaseMessaging will try to initialize  flutter_local_notifications from background (just run app):
https://github.com/bornold/firebase_messaging_local_notifications_npe_example
and example of using this fix:
https://github.com/bornold/firebase_messaging_local_notifications_npe_example/tree/using-fix

[flutter_local_notifications] null checking mainActivity before .getIntent()

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/README.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationBootReceiver.java
flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml
flutter_local_notifications/pubspec.yaml

So I am testing the reschedule functionality on my Huawei device, the local notification is not being rescheduled when I restart my device.
The following enhancement (plus making sure the startup manager don't disable launch on startup) fixes the issue.

[flutter_local_notifications] Support notification reschedule for android during restart / quickboot

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift
flutter_local_notifications/pubspec.yaml

The fix taken from [StackOverflow](https://stackoverflow.com/questions/16706293/ios-nsdate-comparison-works-differently-when-the-24-hour-time-in-date-settings-t/16706425#16706425)
We need to set the date formatter's locale to the special locale that include POSIX string, for example **en_US_POSIX**
Closes #860

[flutter_local_notifications] Fix for issue #860

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/lib/src/platform_specifics/android/notification_sound.dart
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] use NotificationManager for managing channel groups, fixes for initialising Android ThreeTenBP lib

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] switch notification channel deletion to use NotificationManager again

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/pubspec.yaml

Fix the said issue #924 in `flutter_local_notifications\example` app. 
Tested on Android 9.0 Pie. Run on debug build. Works as expected.
Since I didn't have any iOS device, I didn't make any changes in iOS side. 
https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android
https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions

[flutter_local_notifications] update example app to point https placeholder image URLs

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] change how notification ids are checked for equality to avoid scheduled notifications crashing on older Android versions

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
flutter_local_notifications/test/platform_flutter_local_notifications_test.dart

Addresses #938
Just adds an extra boolean option to AndroidNotificationDetails, with test & example.

[flutter_local_notifications] Add support for setUsesChronometer on Android.

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Modify commit() to apply() to avoid framerate falls when scheduling many notifications. commit() is called on the main thread and is blocking to the contrary of apply(), and it should lead to no bug due to asynchronism whatsoever.

[flutter_local_notifications] Replace commit() by apply() in Android implementation to avoid blocking UI thread

---

flutter_local_notifications/README.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
flutter_local_notifications/lib/src/platform_specifics/ios/method_channel_mappers.dart
flutter_local_notifications/lib/src/platform_specifics/ios/notification_details.dart
flutter_local_notifications/lib/src/platform_specifics/macos/method_channel_mappers.dart
flutter_local_notifications/lib/src/platform_specifics/macos/notification_details.dart
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift
flutter_local_notifications/test/platform_flutter_local_notifications_test.dart

This PR adds two platform-specific properties to `NotificationDetails`
- `tag` for Android which can be used for replacing notifications
- `threadIdentifier` for iOS and macOS which can be used for grouping notifications

[flutter_local_notifications] Add tag and threadIdentifier platform-specific properties

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart

[flutter_local_notifications] fix api docs for getNotificationChannels and amend 4.0.1 changelog entry

---

flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift

This fix prevents asking for permissions on the plugin initialization
Fixes https://github.com/MaikuB/flutter_local_notifications/issues/1062

Don't request empty permissions

---

flutter_local_notifications/android/build.gradle

Instead of specifying the compileSdkVersion by the preview name, it is best to use the actual API number, and android-S's version number is 31.
By difference, some machines cannot fetch version "android-S", as it is a preview SDK build, whereas 31 is a non-preview build, and can be fetched by all machines.

[flutter_local_notifications] Update build.gradle - swap "android-S" to 31

---

flutter_local_notifications_platform_interface/CHANGELOG.md
flutter_local_notifications_platform_interface/lib/flutter_local_notifications_platform_interface.dart
flutter_local_notifications_platform_interface/lib/src/helpers.dart
flutter_local_notifications_platform_interface/lib/src/typedefs.dart
flutter_local_notifications_platform_interface/pubspec.yaml

[flutter_local_notifications_platform_interface] moved the SelectNotificationCallback typedef and validateId to platform interface

---

flutter_local_notifications_linux/lib/src/notifications_manager.dart

Fixed https://github.com/MaikuB/flutter_local_notifications/issues/1244

[flutter_local_notifications_linux] Prevent double initialization

---

flutter_local_notifications_linux/lib/src/platform_info.dart

TMPDIR is a standard variable on UNIX/Linux systems, and is often used in containers such as Flatpak to redirect to a temporary folder inside a sandbox. This allows not to make hard bindings to the /tmp directory

[flutter_local_notifications_linux] Using TMPDIR env as a primary temporary path

---

flutter_local_notifications_linux/lib/src/flutter_local_notifications.dart
flutter_local_notifications_linux/lib/src/flutter_local_notifications_platform_linux.dart
flutter_local_notifications_linux/lib/src/model/capabilities.dart
flutter_local_notifications_linux/lib/src/model/hint.dart
flutter_local_notifications_linux/lib/src/model/icon.dart
flutter_local_notifications_linux/lib/src/model/initialization_settings.dart
flutter_local_notifications_linux/lib/src/model/notification_details.dart
flutter_local_notifications_linux/lib/src/notification_info.dart

GNOME refresh the developer portal and removed some of the old links.

[flutter_local_notifications_linux] Replace 'developer.gnome.org' links to 'specifications.freedesktop.org'

---

flutter_local_notifications/pubspec.yaml

[`timezone`](https://pub.dev/packages/timezone) has a new version. Would be great to support it.

[flutter_local_notifications] Increase timezone version dependency

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/IconSource.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/PersonDetails.java
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/platform_specifics/android/enums.dart
flutter_local_notifications/lib/src/platform_specifics/android/icon.dart
flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart

Implements the same change that has been done in #1227 but for icons (e.g. used for `PersonDetails`)

[flutter_local_notifications]: allow byte arrays as source for icons

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fix to refer to custom sound resources by the resource's name instead of resource id

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Clean up from #1388. Relates to #1387

[flutter_local_notifications] remove redundant commit to shared prefs logic and checks for commit during initialisation

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/android/active_notification.dart
flutter_local_notifications/pubspec.yaml

FYI @drstranges that i'll be removing this from the 9.x stable release as I should published the changes in your PR (#1376) as part of a major release

[flutter_local_notifications]remove addition of groupKey to ActiveNotification so that it goes in a major release

---

.gitignore
flutter_local_notifications/lib/src/initialization_settings.dart
flutter_local_notifications_linux/lib/src/model/categories.dart
flutter_local_notifications_linux/test/posix_test.dart
flutter_local_notifications_platform_interface/test/flutter_local_notifications_platform_interface_test.dart
melos.yaml

During the work on #880 I noticed the project could be managed slightly easier rgd. dependencies, tests and so on.
The `melos` package could help with this - now you can run things like this:
```
melos bootstrap
melos exec flutter pub get
melos run test
melos run analyze
```
The `test` commands is probably the most useful as it can run for all the packages.
It is not integrated in the CI process, yet, but could be.

Adds support for melos 

---

flutter_local_notifications/README.md
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/example/linux/flutter/generated_plugin_registrant.cc
flutter_local_notifications/example/linux/flutter/generated_plugin_registrant.h
flutter_local_notifications/example/linux/flutter/generated_plugins.cmake
flutter_local_notifications_linux/lib/src/flutter_local_notifications.dart
flutter_local_notifications_linux/lib/src/flutter_local_notifications_platform_linux.dart
flutter_local_notifications_linux/lib/src/flutter_local_notifications_stub.dart
flutter_local_notifications_linux/lib/src/model/capabilities.dart
flutter_local_notifications_linux/lib/src/model/notification_details.dart
flutter_local_notifications_linux/lib/src/notification_info.dart
flutter_local_notifications_linux/lib/src/notifications_manager.dart
flutter_local_notifications_linux/test/mock/mock.dart
flutter_local_notifications_linux/test/mock/mock_select_notification_callback.dart
flutter_local_notifications_linux/test/mock/mock_typedef.dart
flutter_local_notifications_linux/test/notifications_manager_test.dart
flutter_local_notifications_linux/test/storage_test.dart

All action features that are available in the Desktop Notification Specification have been implemented. Actions such as textbox are not implemented due to the lack of a standardized implementation. The `onSelectNotificationAction` callback currently doesn't work, because `flutter_local_notifications` depends on the old version of `linux_local_notifications_linux` and I can't map `onSelectNotificationAction` to Linux implementation. After the release of Linux plugin, you need to add it here:
https://github.com/MaikuB/flutter_local_notifications/blob/3a9eae23cd723175908d7809a9d58374c4243e16/flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart#L141-L146
For the test, you can change `pubspec.yaml` of  `flutter_local_notifications` this way:
```YAML …
```

[flutter_local_notifications_linux] Add actions support in Linux

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fix crash on calling requestPermissions with default values

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/android/active_notification.dart

Allows users to fetch an active notification tag.
Closes: https://github.com/MaikuB/flutter_local_notifications/issues/1512

[flutter_local_notifications] Add ActiveNotification.tag

---

flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift

update logic on iOS and macOS to set notification categories without querying for existing categories

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/README.md
flutter_local_notifications/example/integration_test/flutter_local_notifications_test.dart
flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart
flutter_local_notifications/lib/src/initialization_settings.dart
flutter_local_notifications/pubspec.yaml

change: throw ArgumentError when trying to initialize LocalNotification without  per Platform settings
add: tests
add: inline docs

[flutter_local_notifications] Throw ArgumentError when trying to initialize LocalNotification without  per Platform settings

---

flutter_local_notifications/README.md

My understanding is that the best way of referring to DST is not "daylight savingS" but "daylight saving", and I put in "time" for completeness for a readme. https://en.wikipedia.org/wiki/Daylight_saving_time
Some headers were level 4 and 5 after a level 2 header, so I bumped them up. I removed extra newlines and added missing ones since most of the doc uses the style of 2 newlines after a header.
---
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications]). The contribution guidelines can be found at https://github.com/MaikuB/flutter_local_notifications/blob/master/CONTRIBUTING.md. Please review this as it contains details on what to follow when submitting a PR.

[flutter_local_notifications] DST, function typo, header and newline consistency in readme

---

flutter_local_notifications/README.md

This fixes the table of contents at https://pub.dev/packages/flutter_local_notifications .
Android and iOS Setup do not work as the emoji breaks the link fragment.
Unfortunately I just realized, that GitHub seems to handle the #️Number Sign emoji differently, so it currently only works on GitHub.
With this fix it would work on pub.dev, but not on GitHub. :neutral_face:

[flutter_local_notifications] Fix table of contents in README

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/example/linux/flutter/generated_plugin_registrant.cc
flutter_local_notifications/example/linux/flutter/generated_plugin_registrant.h
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart

This allows fetching an active notification's StyleInformation.
A typical use-case is appending a new Message to a MessagingStyle
when receiving a push message.
* * *
ATM this is pretty incomplete and only covers my exact use-case. Would you be interested in such a feature?

[flutter_local_notifications] Add getActiveNotificationMessagingStyle

---

flutter_local_notifications/android/build.gradle

Fixes CVE-2022-25647.
This updates an android jar to a version without the vulnerability. Vulnerability is considered HIGH and more info is [here](https://nvd.nist.gov/vuln/detail/CVE-2022-25647#range-7910512)

[flutter_local_notifications] Update gson package for vulnerabilities

---

flutter_local_notifications/example/lib/main.dart
flutter_local_notifications_linux/lib/src/flutter_local_notifications_stub.dart
flutter_local_notifications_linux/lib/src/model/enums.dart
flutter_local_notifications_linux/lib/src/model/icon.dart
flutter_local_notifications_linux/lib/src/notifications_manager.dart
flutter_local_notifications_linux/pubspec.yaml
flutter_local_notifications_linux/test/notifications_manager_test.dart

Adding the `FilePathLinuxIcon` class will allow the developer to specify a custom path in the file system to the icon, if other options, such as `AssetsLinuxIcon`, aren't suitable (for example, the assets path is different from the standard one).
Close #1565

 [flutter_local_notifications_linux] Add support for the file path icons

---

flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/android/categories.dart
flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart

Add all the Android categories values with documentation in AndroidNotificationCategory class from https://developer.android.com/reference/androidx/core/app/NotificationCompat.html#constants_2. 
The goal is make this property more accessible for the users. It results in a little breaking change since the current `category` property is of `String` type. However, I believe it’s worth using it. 
Also, I tried to make it just like LinuxNotificationCategory of Linux package to keep a pattern.

[flutter_local_notifications] add AndroidNotificationCategory to make Android categories more accessible

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fix zonedSchedule error on macOS when matching using dayOfMonthAndTime or dateAndTime

---

flutter_local_notifications/README.md

**Icon design status bar's** previous [link](https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar) redirects to material design > 404.
replaced it with this archived [icon_design_status_bar page](https://android-doc.github.io/guide/practices/ui_guidelines/icon_design_status_bar.html)

[flutter_local_notifications] Documentation: updated dead link

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationChannelDetails.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/platform_specifics/android/enums.dart
flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
flutter_local_notifications/test/android_flutter_local_notifications_test.dart

Allows users to change  AudioAttributes (https://developer.android.com/reference/android/media/AudioAttributes) to the notification sound
Closes: https://github.com/MaikuB/flutter_local_notifications/issues/1519

[flutter_local_notifications]  Add audioAttributesUsage to NotificationDetails

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Other flutter plugins permissions requests can end up triggering onRequestPermissionsResult, so only handle callbacks when we're expecting one to be outstanding.
This fixes a `java.lang.IllegalStateException: Reply already submitted` crash that can occur when other flutter plugins request access to permissions on Android.

[flutter_local_notifications] Check permissionRequestInProgress in onRequestPermissionsResult

---

flutter_local_notifications/pubspec.yaml

With this PR, the right section on pub.dev will show the View/report issues link to GitHub again, like [here](https://pub.dev/packages/android_id) (the show-logic was recently changed).

[flutter_local_notifications] Update pub.dev links

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationAction.java

**Issue -** 
When NotificationAction is used for foreground service, getting the below error.
```
Failed to handle method call
Unhandled Exception: PlatformException(error, Parcelable encountered IOException writing serializable 
object (name = com.dexterous.flutterlocalnotifications.ForegroundServiceStartParameter), null, java.lang.RuntimeException: Parcelable encountered IOException writing serializable 
object (name = com.dexterous.flutterlocalnotifications.ForegroundServiceStartParameter
```
Upon debugging I found that NotificationAction was not implementing Serializable.
**Fix -** 
Making NotificationAction Serializable to support  notification actions when notification is started as foreground service

Crash fix when notification actions is used for foreground service 

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/README.md
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] update readme to include details of a Flutter issue with desugaring enabled on foldable Android devices

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java

[flutter_local_notifications] suppress getParcelableExtra deprecation warning

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ActionBroadcastReceiver.java
flutter_local_notifications/ios/Classes/FlutterEngineManager.m
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fix crash occurring for notification actions that don't have a callback to handle them

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Do not leave behind a stale channel or application context. Undo what onnAttachedToEngine does.

[flutter_local_notifications] Handle onDetachedFromEngine in Android

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

registerWith() is a relic from Flutter embedding v1.

[flutter_local_notifications] Drop registerWith in Android plugin

---

flutter_local_notifications/README.md

Fixes #1769 
Adds the import statement required for AppDelegate.swift and AppDelegate.m to use FlutterLocalNotificationsPlugin's setPluginRegistrantCallback function.
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications]). The contribution guidelines can be found at https://github.com/MaikuB/flutter_local_notifications/blob/master/CONTRIBUTING.md. Please review this as it contains details on what to follow when submitting a PR.

[flutter_local_notifications] Fixes #1769 : Updates readme for iOS Setup

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/utils/LongUtils.java
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fixes parsing of callback handles for notification actions on Android

---

flutter_local_notifications/android/build.gradle
flutter_local_notifications/example/analysis_options.yaml
flutter_local_notifications/example/android/app/build.gradle
flutter_local_notifications/example/android/build.gradle
flutter_local_notifications/example/android/gradle.properties
flutter_local_notifications/example/android/gradle/wrapper/gradle-wrapper.properties
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/example/macos/Flutter/GeneratedPluginRegistrant.swift
flutter_local_notifications/example/pubspec.yaml
flutter_local_notifications/pubspec.yaml
flutter_local_notifications/test/android_flutter_local_notifications_test.dart
flutter_local_notifications/test/ios_flutter_local_notifications_test.dart
flutter_local_notifications/test/macos_flutter_local_notifications_test.dart

Fixes:
```console
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/rexios/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-12.0.3/android/build.gradle'
* What went wrong:
Could not compile build file '/Users/rexios/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-12.0.3/android/build.gradle'.
> startup failed:
General error during conversion: Unsupported class file major version 63
java.lang.IllegalArgumentException: Unsupported class file major version 63
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
at …
```

[flutter_local_notifications] Upgraded Android Gradle Plugin to fix Android build

---

flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/lib/src/platform_specifics/darwin/mappers.dart
flutter_local_notifications/lib/src/platform_specifics/darwin/notification_attachment.dart
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift
flutter_local_notifications/test/ios_flutter_local_notifications_test.dart
flutter_local_notifications/test/macos_flutter_local_notifications_test.dart

This PR implements access to two platform-specific features for customizing attachments to notifications (c.f. https://developer.apple.com/documentation/usernotifications/unnotificationattachment?language=objc). Without them it's very hard to use image attachments at all, because by default the first attachment is used both for a tiny thumbnail (smaller than app logo) and a potentially full screen image on an expanded notification.

[flutter_local_notifications] Implement options to hide or crop attachments in the thumbnail on iOS

---

flutter_local_notifications/README.md

As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications]). The contribution guidelines can be found at https://github.com/MaikuB/flutter_local_notifications/blob/master/CONTRIBUTING.md. Please review this as it contains details on what to follow when submitting a PR.
With such a simple change, hopefully I did things correctly.
https://github.com/MaikuB/flutter_local_notifications/issues/1855

 [flutter_local_notifications] Reference newer flutter_timezone package in readme

---

flutter_local_notifications/README.md
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications_platform_interface/lib/flutter_local_notifications_platform_interface.dart
flutter_local_notifications_platform_interface/lib/src/types.dart

A similar issue is already discussed in #1869.
When calling `getActiveNotifications()` on iOS, with Firebase notifications present, `null` is passed as the required `id` parameter of the `ActiveNotification` class. 
I initially proposed to use `-1` as a default value, so that no exception is thrown, and all notifications can be retrieved on both Android and iOS.
As discussed in the linked issue, there is an identifier in the iOS notification, but as this  is not numerical, it's not trivial to use it. I was aware that `-1` is a magic number, but at least this allows users to get the active notifications on iOS even with Firebase notifications present. 
Instead, the alternative approach is now chosen, we say that the `id` is not a `required` parameter, as it does not exist on every …

[flutter_local_notifications_platform_interface] Make ID nullable to prevent exception for active firebase notifications on iOS

---

flutter_local_notifications/example/lib/main.dart

The notification ID was being incremented after creating the notification, which meant that trying to append a message 10 seconds later created an entirely new notification rather than just being added to the conversation.

[flutter_local_notifications] Fix showMessagingNotification in example

---

flutter_local_notifications/example/lib/main.dart

'subtitle1' is deprecated and shouldn't be used. 'titleMedium' is used instead.

[flutter_local_notifications] textstyle of theme changed in example

---

flutter_local_notifications/lib/src/platform_specifics/android/enums.dart

https://developer.android.com/about/versions/14/changes/fgs-types-required
This can be released now since you don't actually reference the APIs in native code, so we don't have to use preview APIs at all.

[flutter_local_notifications] Adds new Android foreground service types

---

flutter_local_notifications/example/macos/Flutter/GeneratedPluginRegistrant.swift
flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/lib/src/tz_datetime_mapper.dart
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift

[flutter_local_notifications] fixed date parsing on iOS and macOS when specified time is when daylight savings occurs

---

flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift

This PR fixes #1858, also duplicated in #1939.
`NSUserNotification` was deprecated in macOS 10.14. This PR:
- Annotates the methods using that API with `@available(OSX, deprecated: 10.14)`
- Adds some `MARK` comments for improved navigability.
Warnings when building with 10.14 or higher should no longer occur.

[flutter_local_notifications] Fix macOS deprecation warnings

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fix to throw Unimplemented when calling zonedSchedule on Linux

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fixed issue with null schedule mode where recurring notifications would fail to be scheduled as a result

---

flutter_local_notifications/lib/src/platform_specifics/darwin/notification_details.dart

Fixed some documentation typos (`this This` -> `this`).

[flutter_local_notifications] Fix documentation typos

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fixed an issue with null schedule mode for older notifications scheduled using periodicallyShow on Android

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] fixed issue importance level was mapped incorrectly when calling getNotificationChannels()

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Hello,
Thanks for your package. 
There is a conflict with the latest version 16.0.0+1 of flutter_local_notifications. I use another package which also implements `onActivityResult`, so there is a conflict when this package starts `startActivityForResult` with a request code == 2. The flutter_local_notifications package falsely intercepts and processes the request code, resulting in an application crash.
Could you merge this PR to fix the issue please?
Thanks.
Here is the log:
```
E/AndroidRuntime( 3382): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.dexterous.flutterlocalnotifications.PermissionRequestListener.complete(boolean)' on a null object reference
E/AndroidRuntime( 3382): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotifications …
```

[flutter_local_notifications] Fix conflict with other plugins (onActivityResult)

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

`requestExactAlarmsPermission` opened the app list screen for alarm and reminder settings.
Fixed to open the alarm setting screen of the application.
ACTION_REQUEST_SCHEDULE_EXACT_ALARM's Document
https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_SCHEDULE_EXACT_ALARM

[flutter_local_notifications] open the alarm settings screen specific to using app

---

flutter_local_notifications/README.md

Environment:
_Dart **3.2.0-42.1.beta** 
Flutter **3.14.0-0.1.pre**
flutter_local_notifications: ^15.1.2_
Convert to named arguments and remove const from constructor invocation as getting compilation error

[flutter_local_notifications] Update README.md to fix compile error

---

flutter_local_notifications/README.md
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/lib/flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/darwin/notification_enabled_options.dart
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift
flutter_local_notifications/test/ios_flutter_local_notifications_test.dart
flutter_local_notifications/test/macos_flutter_local_notifications_test.dart

With this PR we add ability to check notification permissions for both iOS and macOS.
We can check if notifications is just enabled or if there is some specific type is enabled (like alert, badge, etc).
---
For iOS we use `UNUserNotificationCenter` for version 10 or above and `UIApplication.sharedApplication.currentUserNotificationSettings` for 9 and less (with ignore of critical and provisional).
Both version was tested with iOS simulator.
---
For macOS we just use `UNUserNotificationCenter`.
---
In both OS we separately check for provisional, because there can be either authorized status or provisional.

[flutter_local_notifications] Check permissions for iOS and macOS

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

…ence
As this repository hosts multiple packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications]). Should the PR more than one package than please prefix the title of the PR with [various] The contribution guidelines can be found at https://github.com/MaikuB/flutter_local_notifications/blob/master/CONTRIBUTING.md. Please review this as it contains details on what to follow when submitting a PR.

[flutter_local_notifications] setupAlarm method: handle ScheduleMode.useAllowWhileIdle() called on null

---

flutter_local_notifications/ios/Resources/PrivacyInfo.xcprivacy

In relation to #2177
I assumed that UserDefaults is being used for push notification settings in this code.
```objective-c
NSDictionary *persistedPresentationOptions =
[[NSUserDefaults standardUserDefaults]
dictionaryForKey:PRESENTATION_OPTIONS_USER_DEFAULTS];
bool presentAlert = false;
bool presentSound = false;
bool presentBadge = false;
bool presentBanner = false;
bool presentList = false;
if (persistedPresentationOptions != nil) {
presentAlert = [persistedPresentationOptions[PRESENT_ALERT] isEqual:@YES];
presentSound = [persistedPresentationOptions[PRESENT_SOUND] isEqual:@YES];
presentBadge = [persistedPresentationOptions[PRESENT_BADGE] isEqual:@YES];
presentBanner = [persistedPresentationOptions[PRESENT_BANNER] isEqual:@YES];
presentList = [persistedPresentationOptions[PRESENT_LIST] …
```

[flutter_local_notifications] added reason for using User Defaults API to iOS privacy manifest

---

flutter_local_notifications/README.md

[flutter_local_notifications] Updated docs to reflect actual iOS pending notifications limit behaviour

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_channel.dart
flutter_local_notifications/test/android_flutter_local_notifications_test.dart

Added variable "audioAttributesUsage" in AndroidNotificationChannel  to create a channel with audioAttributesUsage in the beginning.
This is need when we need to alert sound on mute/silent.
Related to #1964

[flutter_local_notifications] Added AudioAttributesUsage for AndroidNotificationChannel

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] coleasce null audio attributes when mapping notification channel

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
flutter_local_notifications/example/android/app/src/debug/AndroidManifest.xml
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift
flutter_local_notifications/pubspec.yaml
flutter_local_notifications/test/android_flutter_local_notifications_test.dart
flutter_local_notifications/test/ios_flutter_local_notifications_test.dart
flutter_local_notifications/test/macos_flutter_local_notifications_test.dart
flutter_local_notifications_platform_interface/CHANGELOG.md
flutter_local_notifications_platform_interface/lib/flutter_local_notifications_platform_interface.dart
flutter_local_notifications_platform_interface/lib/src/helpers.dart
flutter_local_notifications_platform_interface/pubspec.yaml

Add an option to set custom time for periodically showed notifications.
The problem that I have encountered on iOS devices is that repeating interval must be set to 60 seconds minimum, but I don't think that is the problem for real use case scenarios.
**Sample usage:**
```
await flutterLocalNotificationsPlugin.periodicallyShowWithDuration(
1,
'repeating period title',
'repeating period body',
const Duration(minutes: 5),
androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
);
```

[flutter_local_notifications] Add custom repeat interval - periodicallyShowWithDuration method

---

flutter_local_notifications_linux/CHANGELOG.md
flutter_local_notifications_linux/lib/src/flutter_local_notifications.dart
flutter_local_notifications_linux/pubspec.yaml

[flutter_local_notification_linux] fixed definition and registration of Linux implementation

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart
flutter_local_notifications/pubspec.yaml

Follow up to #2371 and relates to #2368 
As the Linux package now handles registering the Linux implementation, the app-facing package no longer needs to do this

[flutter_local_notifications] updated plugin to no longer register Linux implementation

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ActionBroadcastReceiver.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

Notifications with tags were not cancelled when an action gets invoked.

[flutter_local_notifications_android] Fix cancel notification with tag in action receiver

---

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java

As discussed in #2309
We deployed the fix to production and we see no more errors 🥳

[flutter_local_notifications] fix: handle exception while loading resource name

---

flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/pubspec.yaml
flutter_local_notifications/test/android_flutter_local_notifications_test.dart
flutter_local_notifications/test/ios_flutter_local_notifications_test.dart
flutter_local_notifications/test/macos_flutter_local_notifications_test.dart

My app initializes the plugin like this:
```dart
final localNotificationsPlugin = FlutterLocalNotificationsPlugin();
await localNotificationsPlugin.initialize(
...
);
...
```
To test this I want to mock the plugin like this:
```dart
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';
import 'package:mocktail/mocktail.dart';
class _LocalNotificationsPlatformMock extends Mock
with MockPlatformInterfaceMixin
implements FlutterLocalNotificationsPlatform {}
void main() {
late FlutterLocalNotificationsPlatform localNotificationsPlatform;
setUp(() {
localNotificationsPlatform = _LocalNotificationsPlatformMock();
FlutterLocalNotificationsPlatform.instance = …
```

[flutter_local_notifications] fix: Fix platform initialization to allow mocking

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/README.md
flutter_local_notifications/android/build.gradle
flutter_local_notifications/ios/flutter_local_notifications.podspec
flutter_local_notifications/macos/flutter_local_notifications.podspec

Updated the plugin's minimum OS requirements to align with minimum Flutter 3.13 requirement.
Reference https://github.com/flutter/website/blob/3d18ab48218101493af84953b71eac0cc6781fdd/src/reference/supported-platforms.md

[flutter_local_notifications] updated minimum OS requirements to align with Flutter 3.13

---

.github/workflows/validate.yml

The text in the parentheses represented the language/framework used to write/run the tests that need to be executed. Updated these to better indicate that there are tests written in Dart for the Windows implementation of the plugin

[various] rename test related jobs in GitHub validate workflow

---

flutter_local_notifications_windows/src/plugin.cpp

A `std::vector` didn't have a starting size, which messed up the Windows APIs. Windows builds will work in release EXEs but will fail the `init()` call in MSIX, so this should be patched before the initial Windows release

[flutter_local_notifications_windows] Fix `init()` on Windows MSIX

---

flutter_local_notifications/README.md

Removed the duplicate `Important` notice in the README and cleaned up the text

[flutter_local_notifications] Fixed README notice

---

.github/workflows/format.yml
.github/workflows/validate.yml
flutter_local_notifications/example/android/app/build.gradle
flutter_local_notifications/example/android/app/src/debug/AndroidManifest.xml
flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml
flutter_local_notifications/example/android/app/src/profile/AndroidManifest.xml
flutter_local_notifications/example/android/build.gradle
flutter_local_notifications/example/android/gradle.properties
flutter_local_notifications/example/android/gradle/wrapper/gradle-wrapper.properties
flutter_local_notifications/example/android/settings.gradle

Followed https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
and updated AGP and kotlin versions.

[flutter_local_notifications] Update gradle versions and declarations for example app

---

flutter_local_notifications/pubspec.yaml

Follow up to https://github.com/MaikuB/flutter_local_notifications/pull/2497 where Windows dependency should've been bumped

[flutter_local_notifications] bumped Windows dependency

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/README.md
flutter_local_notifications/android/build.gradle
flutter_local_notifications/example/android/app/build.gradle
flutter_local_notifications/pubspec.yaml

[flutter_local_notifications] bumped compileSdk to 35

---

flutter_local_notifications/CHANGELOG.md
flutter_local_notifications/example/android/.gitignore
flutter_local_notifications/example/pubspec.yaml

Done to reduce Java 8 compatibility warnings

[flutter_local_notifications] bumped multiple dependencies used by example app

---

flutter_local_notifications_linux/pubspec.yaml
flutter_local_notifications_platform_interface/CHANGELOG.md
flutter_local_notifications_platform_interface/pubspec.yaml
flutter_local_notifications_windows/pubspec.yaml

Also follows up on https://github.com/MaikuB/flutter_local_notifications/pull/2543 to align the platform interface version referenced by Windows and Linux plugin

[various] bumped minimum plugin_platform_interface version

---

flutter_local_notifications/README.md
flutter_local_notifications/example/android/app/proguard-rules.pro

Restore proguard-rules and doc for versions v18 and lower.
* https://github.com/MaikuB/flutter_local_notifications/pull/2440
* https://github.com/MaikuB/flutter_local_notifications/issues/408#issuecomment-2661744363

[flutter_local_notification] Restore proguard-rules for v18 and lower

---

flutter_local_notifications/README.md

A space was preventing the link from properly rendering.
As this repository hosts multiple packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications]). Should the PR more than one package than please prefix the title of the PR with [various] The contribution guidelines can be found at https://github.com/MaikuB/flutter_local_notifications/blob/master/CONTRIBUTING.md. Please review this as it contains details on what to follow when submitting a PR.

[flutter_local_notifications] fix: typo in README

---

flutter_local_notifications/README.md

Removed wrong opening parenthesis.

[flutter_local_notifications] Fix typo in README.md

---

flutter_local_notifications/example/ios/Runner.xcodeproj/project.pbxproj
flutter_local_notifications/example/ios/Runner/RunnerDebug.entitlements
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/ios/flutter_local_notifications/Sources/flutter_local_notifications/FlutterLocalNotificationsPlugin.m
flutter_local_notifications/lib/src/platform_specifics/darwin/mappers.dart
flutter_local_notifications/lib/src/platform_specifics/darwin/notification_details.dart
flutter_local_notifications/macos/flutter_local_notifications/Sources/flutter_local_notifications/FlutterLocalNotificationsPlugin.swift
flutter_local_notifications/test/ios_flutter_local_notifications_test.dart
flutter_local_notifications/test/macos_flutter_local_notifications_test.dart

This PR adds support for Critical Alert notifications on iOS/macOS platforms. Critical Alert notifications are a special type of notification that can break through Do Not Disturb and silent mode settings, requiring specific entitlements from Apple.
Reference: https://developer.apple.com/documentation/usernotifications/unnotificationsound/criticalsoundnamed(_:withaudiovolume:)
Related issue: https://github.com/MaikuB/flutter_local_notifications/issues/528
- Add settings about Critical Alert volume. Ability to set critical sound volume (between 0.0 and 1.0)
- New example demonstrating Critical Alert functionality
- Added necessary entitlements file for debug builds
* I tried to add it to the release build too, but the Critical Alert entitlement cannot actually be added without applying to …

[flutter_local_notifications] Add setting for ios critical alert volume

---

flutter_local_notifications/README.md
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationChannelDetails.java
flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java
flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml
flutter_local_notifications/example/lib/main.dart
flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart
flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_channel.dart
flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
flutter_local_notifications/test/android_flutter_local_notifications_test.dart

Closes #1211 
- Adds new `bypassDnd` and `channelBypassDnd` options for `AndroidNotificationChannel` and `AndroidNotificationDetails` respectively
- Adds `hasNotificationPolicyAccess()` and `requestNotificationPolicyAccess()` methods to `AndroidFlutterLocalNotificationsPlugin`
- Adds relevant buttons to example
- Adds README-entry

[flutter_local_notifications] Support bypassing DnD-settings on Android

---

flutter_local_notifications/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
flutter_local_notifications/example/pubspec.yaml
flutter_local_notifications/macos/flutter_local_notifications/Sources/flutter_local_notifications/FlutterLocalNotificationsPlugin.swift

Remove unnecessary macOS 10.14 check since [Flutter's lowest supported macOS version is 10.14](https://docs.flutter.dev/deployment/macos).
> The minimum macOS version that your app supports. Flutter supports deploying apps to macOS 10.14 (Mojave) and later.
Bump dependency versions of the example app.

[flutter_local_notifications] Remove redundant macOS version check

---

flutter_local_notifications/android/build.gradle

Bumps robolectric to its latest version.
<details>
<summary>🛠️ Fixes this error</summary>
```
com.dexterous.flutterlocalnotifications.IsolatePreferencesTest > saveAndGet_ShouldReturnCorrectValues FAILED
java.lang.NoClassDefFoundError at Shadows.java:2457
Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
Caused by: java.lang.IllegalArgumentException at ClassReader.java:199
com.dexterous.flutterlocalnotifications.models.NotificationActionTest > constructor_populatesAllFields FAILED
java.lang.NoClassDefFoundError at Shadows.java:2457
Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
Caused by: java.lang.IllegalArgumentException at ClassReader.java:199
2 tests completed, 2 failed
> Task :flutter_local_notifications:testDebugUnitTest FAILED
``` …

fix: bump robolectric
