MaikuB/flutter_local_notifications

CHANGELOG.md, android/src/main/java/com/dexterous/flutterlocalnotifications/BigTextStyleInformation.java, android/src/main/java/com/dexterous/flutterlocalnotifications/DefaultStyleInformation.java, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/NotificationDetails.java, example/lib/main.dart, lib/platform_specifics/android_styles/big_text_style_information.dart, lib/platform_specifics/android_styles/default_style_information.dart, lib/platform_specifics/notification_details/notification_details_android.dart, pubspec.yaml
Fixes deprecation warning issue raised in #5
=> Fix deprecation warning and add support to format title and content body for Android notifications

CHANGELOG.md, README.md, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, example/lib/main.dart, lib/platform_specifics/android/notification_details_android.dart, pubspec.yaml, test/flutter_local_notifications_test.dart
Also cleaned up some code around deleting scheduled notifications, thanks to radzish for pointing it out
=>  Add ability to specify if notifications are ongoing or should autocancel. Bug fix in handling cancel all notifications method

CHANGELOG.md, README.md, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, example/lib/main.dart, lib/flutter_local_notifications.dart, lib/platform_specifics/android/notification_details_android.dart, pubspec.yaml
=> Add ability to set the colour for Android notifications

CHANGELOG.md, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, example/lib/main.dart, pubspec.yaml
=> Fix bug with applying ongoing and autoCancel properties

CHANGELOG.md, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, pubspec.yaml
=> Fix issue with showDailyAtTime and showWeeklyAtDayAndTime where time occurred in the past and caused notification to trigger instantly

CHANGELOG.md, README.md, pubspec.yaml
Includes correction as raised in #62
=> README updates

CHANGELOG.md, README.md, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java, example/lib/main.dart, lib/src/flutter_local_notifications.dart, lib/src/platform_specifics/android/enums.dart, lib/src/platform_specifics/android/styles/big_picture_style_information.dart, lib/src/platform_specifics/android/styles/big_text_style_information.dart, lib/src/platform_specifics/android/styles/default_style_information.dart, lib/src/platform_specifics/android/styles/inbox_style_information.dart, lib/src/platform_specifics/android/styles/style_information.dart, pubspec.yaml
=> Documentation updates and fix a couple of Android issues

CHANGELOG.md, README.md, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, example/lib/main.dart, lib/src/platform_specifics/android/notification_details.dart, pubspec.yaml
Includes feature request from #83
=> Mappings for setOnlyAlertOnce and setShowBadge

CHANGELOG.md, README.md, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, example/lib/main.dart, lib/src/platform_specifics/android/notification_details.dart, pubspec.yaml
=> Android only: Added ability to show progress notifications and updated example app to demonstrate how to display them

example/lib/main.dart
=> Remove port from main.dart

CHANGELOG.md, README.md, android/build.gradle, example/android/app/build.gradle
=> change back to API 27

CHANGELOG.md, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/styles/BigPictureStyleInformation.java, example/lib/main.dart, lib/src/platform_specifics/android/styles/big_picture_style_information.dart, pubspec.yaml
=> 0.4.3 release

CHANGELOG.md, README.md, example/ios/Runner/AppDelegate.m, example/lib/main.dart, ios/Classes/FlutterLocalNotificationsPlugin.m, lib/src/flutter_local_notifications.dart, lib/src/platform_specifics/ios/initialization_settings.dart, pubspec.yaml
=> 0.4.4 release

CHANGELOG.md, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationChannelAction.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, example/lib/main.dart, lib/src/platform_specifics/android/enums.dart, lib/src/platform_specifics/android/notification_details.dart, pubspec.yaml
Adds notification channel management options #167
=> 0.5.2 release

CHANGELOG.md, android/build.gradle, android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/lib/main.dart, lib/src/platform_specifics/android/notification_details.dart, pubspec.yaml
Add ability to specifiy LED light colour for Android notifications #121
=> 0.7.0 release

README.md
There is no more 'recieve' finally. 😂
=> Fix typo with 'recieve'

CHANGELOG.md, ios/Classes/FlutterLocalNotificationsPlugin.m, pubspec.yaml
=> 0.8.2 release

CHANGELOG.md, example/ios/.gitignore, example/ios/Podfile.lock, example/lib/main.dart, ios/Classes/FlutterLocalNotificationsPlugin.m, pubspec.yaml
=> 0.8.4 release

CHANGELOG.md, README.md, pubspec.yaml
=> update readme with Swift example for cancelling local notifications in AppDelegate

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notification] Add timeoutAfter and category to AndroidNotificationDetails

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/example/pubspec.yaml, flutter_local_notifications/lib/src/helpers.dart, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] lower Flutter SDK to hotfix 5 due to pub issues and optimise usage of Gson

flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m, flutter_local_notifications/ios/Classes/NotificationDetails.h, flutter_local_notifications/lib/src/platform_specifics/ios/notification_details.dart
Able to set badge number for iOS notification
=> [flutter_local_notifications] add ability to set badge number on iOS

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] update info on permissions request feature and firebase_messaging plugin compatibility issues

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/example/pubspec.yaml, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fix bug with calling getNotificationAppLaunchDetails() on Android

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/SoundSource.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, flutter_local_notifications/example/android/app/src/main/java/com/dexterous/flutterlocalnotificationsexample/MainActivity.java, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/lib/flutter_local_notifications.dart, flutter_local_notifications/lib/src/platform_specifics/android/enums.dart, flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart, flutter_local_notifications/lib/src/platform_specifics/android/notification_sound.dart
=> [flutter_local_notifications] change the type for AndroidNotificationDetails' sound property and support passing URIs for the sound

flutter_local_notifications/lib/src/platform_specifics/android/notification_channel.dart, flutter_local_notifications/test/platform_flutter_local_notifications_test.dart
=> [flutter_local_notifications] add tests to verify parameters sent to platform channels

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationChannelDetails.java, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart, flutter_local_notifications/pubspec.yaml, flutter_local_notifications/test/platform_flutter_local_notifications_test.dart
=> [flutter_local_notifications] add ability to delete notification channels

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/lib/src/platform_specifics/android/initialization_settings.dart, flutter_local_notifications/lib/src/platform_specifics/android/notification_channel.dart, flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart, flutter_local_notifications/pubspec.yaml, flutter_local_notifications/test/platform_flutter_local_notifications_test.dart
Fixes https://github.com/MaikuB/flutter_local_notifications/issues/139
This commit lets users add any extra android notification flags not handled specifically by AndroidNotificationDetails`
=> [flutter_local_notifications] Add extra flags for Android notifications

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/example/ios/Runner.xcodeproj/project.pbxproj, flutter_local_notifications/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fix code around calling iOS completion handlers

flutter_local_notifications/CHANGELOG.md
=> [flutter_local_notifications] add link to GitHub issue in changelog

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fix issues around onSelectNotification callback and getNotificationAppLaunchDetails() when resuming Android app

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
Missing commit to format Android code changes in PR #755
=> [flutter_local_notifications] format Android code

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] guard code getting intent from activity in case activity doesn't exist

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/pubspec.yaml
Reverts MaikuB/flutter_local_notifications#785
=> Revert "[flutter_local_notifications] Fix dependency error in Flutter 1.22"

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
=> [flutter_local_notifications] Add Null-Safety to FullScreen Intent Check

.cirrus.yml, flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] update platform dependency version constraint

flutter_local_notifications/README.md
- updates the docs
If you find this helpful, please mark the [PR with the label](https://hacktoberfest.digitalocean.com/hacktoberfest-update) `hacktoberfest-accepted`
=> [flutter_local_notifications] update ios initialization in docs

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] update example app to include code for weekly Monday 10:00AM notification

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m, flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart, flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fix null title causing issues with iOS notifications

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fix issue with duplicate pending notifications on Android

flutter_local_notifications/README.md
=> Fix anchor link

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] update readme around android setup

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
=> fix ClassNotFoundException when use activity-alias

.cirrus.yml
=> [flutter_local_notifications] use master channel to build example macos app

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] bump plugin to 4.0.1+2 and include details

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart, flutter_local_notifications/pubspec.yaml
Includes minor import cleanup. Closes #1105 and #1109
=> [flutter_local_notifications] update readme around initialisation and testing

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] re-add attributes to example app for full-screen intent notifications on Android

flutter_local_notifications/README.md
=> [flutter_local_notifications] Readme: remove item that is not exist from TOC

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] address unchecked operation and allow createNotificationChannel to be called even when channel exists already

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/example/pubspec.yaml
=> [flutter_local_notifications] bump example app dependencies and use all variant of the IANA timezone DB

flutter_local_notifications/android/build.gradle, flutter_local_notifications/example/android/build.gradle
Replaced jcenter() with mavenCentral(), as jcenter() is deprecated.
Closes #1380
=> [flutter_local_notifications] Replace jcenter

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationBootReceiver.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] use executor service to commit to Android shared prefs in background and pass method channel result once committed

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fix NPE after committing to shared preferences

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationBootReceiver.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] Revert executor service changes

.github/workflows/format.yml
Pulled this out separately from #880 as it would be valuable to have on its own
Credit to @Kavantix who originally worked on it in https://github.com/ened/flutter_local_notifications/pull/2
=> [flutter_local_notifications] update workflow to format swift and objective c code

flutter_local_notifications/pubspec.yaml, flutter_local_notifications_linux/CHANGELOG.md, flutter_local_notifications_linux/lib/src/dbus_wrapper.dart, flutter_local_notifications_linux/pubspec.yaml, flutter_local_notifications_linux/test/notifications_manager_test.dart
A simple upgrade to DBus ^0.6.0, which now features named parameters.
=> [flutter_local_notifications_linux] DBus 0.6 upgrade

.cirrus.yml, melos.yaml
Continues on #1433 where support for melos was added
=> Rework CI to use melos

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart, flutter_local_notifications/pubspec.yaml
Closes #1378 and #1448.
Change is already in 10.0.0 prerelease but bringing forward to 9.3.0 so it's promoted to stable release sooner
=> [flutter_local_notifications] use apply() to save changes to shared preferences

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] remove dart:ffi import

flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications]). The contribution guidelines can be found at https://github.com/MaikuB/flutter_local_notifications/blob/master/CONTRIBUTING.md. Please review this as it contains details on what to follow when submitting a PR.
=> omiting "io.flutter.embedding.android.SplashScreenDrawable"

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
Sorry, I missed this in my previous PR.
=> [flutter_local_notifications] Fix getActiveNotificationMessagingStyle with tag

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fix crash when push notification happens on macOS

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/lib/src/platform_specifics/android/method_channel_mappers.dart, flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart, flutter_local_notifications/test/android_flutter_local_notifications_test.dart
#1409 
I'll put a badge on the Android home app.
Please give me a review. I want to use this feature in my app so I want it merged.
Flutter_local_notificationsn has always helped me. Thanks for the good plugin.
This is what it looks like in Microsoft Launcher.
=> [flutter_local_notifications] show number for Android

flutter_local_notifications_linux/CHANGELOG.md, flutter_local_notifications_linux/pubspec.yaml
=> [flutter_local_notifications_linux] lowered version constraint of path package specified in linux plugin

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md
=> [flutter_local_notifications] updated docs to mention compileSdkVersion changes needed for 9.8.0

flutter_local_notifications/README.md
update IOS general setup document in flutter_local_notification/README.md
=> [flutter_local_notifications] update document issue #1684

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ForegroundService.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationBootReceiver.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java, flutter_local_notifications/example/linux/flutter/generated_plugin_registrant.cc, flutter_local_notifications/example/linux/flutter/generated_plugins.cmake, flutter_local_notifications/example/macos/Flutter/GeneratedPluginRegistrant.swift
=> [flutter_local_notifications] use type safer intent APIs on Android API 33+

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/pubspec.yaml
This updates the `timezone` package.
=> [flutter_local_notifications] Update timezone

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/example/macos/Flutter/GeneratedPluginRegistrant.swift, flutter_local_notifications/example/pubspec.yaml
=> [flutter_local_notifications] remove rxDart from example app and remove unused dependency

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/example/pubspec.yaml, flutter_local_notifications/pubspec.yaml, flutter_local_notifications_linux/CHANGELOG.md, flutter_local_notifications_linux/pubspec.yaml
=> [flutter_local_notifications_linux] bumped dbus dependency

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m
=> [flutter_local_notifications] suppress deprecation warnings on iOS relating to old notification APIs

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] updated readme to add guidance on adding timezone as a direct dependency

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ActionBroadcastReceiver.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] lookup callback after Flutter engine is created

flutter_local_notifications/README.md
In this way the permission request is easier to understand.
=> [flutter_local_notifications] update code snippet in readme on requesting permissions on Android

flutter_local_notifications/README.md
=> [flutter_local_notifications] Recommend WindowManager to fix Android 12L+ bugs

flutter_local_notifications/example/lib/main.dart
=> [flutter_local_notifications] replaced placeholder.com with dummyimage.com in example app due to Cloudflare blocking requests

flutter_local_notifications/README.md
Update readme code snippet to accept null values in notificationAppLaunchDetails variable
=> Update readme code snippet to accept null values

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/pubspec.yaml, flutter_local_notifications/test/flutter_local_notifications_test.dart, flutter_local_notifications_linux/CHANGELOG.md, flutter_local_notifications_linux/pubspec.yaml, flutter_local_notifications_platform_interface/CHANGELOG.md, flutter_local_notifications_platform_interface/pubspec.yaml
=> [various] prepare for 14.0.0 stable release

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java
=> [flutter_local_notifications] Handle scheduled notification receiver null notification

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/example/android/build.gradle, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fixed issue to cancel notification on android when user taps on an action that shows a UI whilst app is terminated

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java, flutter_local_notifications/example/ios/Runner.xcodeproj/project.pbxproj, flutter_local_notifications/example/macos/Runner.xcodeproj/project.pbxproj
=> [flutter_local_notifications] fixed custom sound not working in example app on iOS and macOS

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m, flutter_local_notifications/lib/src/platform_specifics/darwin/initialization_settings.dart, flutter_local_notifications/lib/src/platform_specifics/darwin/mappers.dart, flutter_local_notifications/lib/src/platform_specifics/darwin/notification_details.dart, flutter_local_notifications/macos/Classes/FlutterLocalNotificationsPlugin.swift, flutter_local_notifications/pubspec.yaml, flutter_local_notifications/test/ios_flutter_local_notifications_test.dart, flutter_local_notifications/test/macos_flutter_local_notifications_test.dart
=> [flutter_local_notifications] added supported for banner and list presentation options for iOS and macOS

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/android/src/main/AndroidManifest.xml, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/lib/src/flutter_local_notifications_plugin.dart, flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart, flutter_local_notifications/pubspec.yaml, flutter_local_notifications/test/android_flutter_local_notifications_test.dart
=> [flutter_local_locations] added ability to request permission to schedule exact alarms and updated permissions and receivers in plugins' manifest file

flutter_local_notifications/README.md
- Updated params of `onDidReceiveLocalNotification`.
- Updated the `DarwinNotificationAction` constructor.
=> Fix outdated examples in README.md

flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
=> [flutter_local_notifications] fixed link in Android plugin code that referenced old behaviour a fix was for

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/ios/Resources/PrivacyInfo.xcprivacy, flutter_local_notifications/ios/flutter_local_notifications.podspec, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] added privacy manifest

flutter_local_notifications/README.md
Fix: Typos
Add: if-null in title,body
=> [flutter_local_notifications] Update README.md

.github/workflows/validate.yml, flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] fixed issue with casting message timestamps

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java, flutter_local_notifications/example/lib/main.dart, flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m, flutter_local_notifications/lib/src/platform_flutter_local_notifications.dart, flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
added ability to request full-screen intent permission
=> [flutter_local_notifications] added requestFullScreenIntentPermission() method

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/README.md, flutter_local_notifications/pubspec.yaml
=> [flutter_local_notifications] updated gradle setup steps around specifying AGP version

flutter_local_notifications/CHANGELOG.md
Done in preparation for a 17.2.2 patch release
=> [flutter_local_notifications] created 17.2.2 changelog entries

flutter_local_notifications/README.md
=> [flutter_local_notifications] Fix typo for README

flutter_local_notifications/CHANGELOG.md, flutter_local_notifications/macos/Resources/PrivacyInfo.xcprivacy, flutter_local_notifications/macos/flutter_local_notifications.podspec
=> [flutter_local_notifications] added privacy manifest file to macOS implementation

flutter_local_notifications/README.md
=> [flutter_local_notifications] added Kotlin-based Gradle setup code snippets

flutter_local_notifications/pubspec.yaml
Changed dependencies from prerelease to stable versions
=> [various] prepare for 19.0.0 stable release follow-up 

flutter_local_notifications/example/android/app/build.gradle, flutter_local_notifications/example/android/gradle.properties, melos.yaml
- Aligns NDK version with what's specified by Flutter
- Fixes Java heap space issue by updating JVM args to align with defaults provided with new apps created through Flutter 3.32's SDK
Note: Flutter 3.32 is current stable version as of writing this
=> [flutter_local_notifications] fixed Android example app build to work with current Flutter stable version (3.32)

flutter_local_notifications_windows/src/plugin.cpp, flutter_local_notifications_windows/src/utils.cpp, flutter_local_notifications_windows/src/utils.hpp
As this repository hosts multiple packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications]). Should the PR more than one package than please prefix the title of the PR with [various] The contribution guidelines can be found at https://github.com/MaikuB/flutter_local_notifications/blob/master/CONTRIBUTING.md. Please review this as it contains details on what to follow when submitting a PR.
Fixed https://github.com/MaikuB/flutter_local_notifications/issues/2648#issuecomment-3061090763
=> [flutter_local_notifications_windows] fix(windows): non-ascii characters in DisplayName
